### ISSUE TITLE
-XX:-UseParNewGC crashes IDEA 2019.2 at startup

### ISSUE THREAD

**Issue by davemerrill** [FoxxMD/intellij-jvm-options-explained#3]
The recommended -XX:-UseParNewGC setting crashes IDEA 2019.2 at startup.

Note that 2019.2 has a bug that misreports all invalid JVM settings as "MaxJavaStackTraceDepth=-1 is outside the allowed range", see https://youtrack.jetbrains.com/issue/IDEA-212194. That's expected to be fixed in 2019.2.1, but I don't expect this setting to work then, just the error to be reported correctly.

**Comment by FoxxMD** [comment]
Thanks for the heads up, I've updated the recommended options and the option combos in the GC section.

In regards to TraceDepth -- since I don't have it in the recommended options and in its description I don't recommend `-1` I'm going to just leave as-is for now. It's still listed on [Jetbrain's jvm page](https://intellij-support.jetbrains.com/hc/en-us/articles/206544869-Configuring-JVM-options-and-platform-properties) so if 2019.2.1 comes and goes and they haven't updated i'll make a note of it here.

**Comment by davemerrill** [comment]
Guess I wasn't clear enough about the MaxJavaStackTraceDepth issue. The problem isn't with that setting, it's that 2019.2 incorrectly reports ANY invalid JVM settings as "MaxJavaStackTraceDepth=-1 is outside the allowed range".

Don't think you need to change anything in that regard, I just mentioned it because that's the error IDEA will report from the actually-invalid -XX:-UseParNewGC setting. I figured which one was the problem by commented them out one by one.

**Comment by FoxxMD** [comment]
Ah ok that makes sense!
